apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ingress-demo
  region: us-east-1
  tags:
    owner: afro-it-solutions
    bu: ait-africa
    project: ingress-demo

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  withOIDC: true

managedNodeGroups:
  - name: eks-private-nodegroup
    instanceType: t3.small
    minSize: 4
    maxSize: 4
    privateNetworking: true
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: false
        certManager: yes
        ebs: false
        fsx: false
        efs: false
        albIngress: true
        xRay: false
        cloudWatch: false
    labels:
      lifecycle: ec2-autoscaler
